### ISSUE TITLE
[Feature] login and identify user using httpOnly cookies for browsers requests

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/authentication-service#18]

**Comment by ShiraRotman** [comment]
We can send the token as a cookie.

**Comment by ShiraRotman** [comment]
I've read a bit about it, and I think only the access token should be sent as a cookie. The refresh token can be stored on a separate microservice that will handle getting a new access token from the authentication service and sending it back to the client. See [here](https://auth0.com/docs/tokens/token-storage).
