### ISSUE TITLE
[Feature] Ability to change myself data

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/authentication-service#25]
on endpoint `POST /api/me` should have the ability to change my own data, such as:
name, email, password, etc..

**Comment by dennis-pg** [comment]
Can look into this

**Comment by karmanya007** [comment]
Is this feature being actively being worked upon. If not I would like to work on it. I have already implemented such feature in one of my [project](https://github.com/karmanya007/Natours).

**Comment by davidmeirlevy** [comment]
We're now working on a blocking issue regarding cookies and tokens mechanism.
It will be merged in next few hours, so I recommend to start working on the latest version that will be here soon.

**Comment by karmanya007** [comment]
Okay. 😄

**Comment by davidmeirlevy** [comment]
done by me.
