### ISSUE TITLE
Server/routes/me.ja

### ISSUE THREAD

**Issue by knowledgeReignsSupreme** [greenpress/authentication-service#32]
Hello everyone. Casually browsing this repo and I found the me.js (which includes 2 endpoints) file under the "routes" directory. 
Correct me if I'm wrong, but this file should be in the Controllers directory.
Same thing for the refresh-tokens under the "routes" directory which should've been somewhere else..

If possible, I would like to make the changes myself.
Thanks!

**Comment by davidmeirlevy** [comment]
@knowledgeReignsSupreme yes, you're right.
It started small and grow a little, and we didn't have the time to refactor this part.

We'd really love you help!

Thanks.

**Comment by knowledgeReignsSupreme** [comment]
@davidmeirlevy Lovely. Thank you

**Comment by knowledgeReignsSupreme** [comment]
I opened a new PR.
https://github.com/greenpress/authentication-service/pull/33
@davidmeirlevy

**Comment by davidmeirlevy** [comment]
Merged. 

Thanks!

**Comment by knowledgeReignsSupreme** [comment]
My pleasure. Please let me know if you need anything else
