### ISSUE TITLE
[BUG] When calling an endpoint with expired token, response is pending

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/authentication-service#5]
Didn't find the exact moment, but sometimes, calling to _**/api/me**_  with expired token or wrong token - the response get timed out.

I probably forgot to handle a specific use case about token expiration or a case when the token has been replaced but the user still uses the previous token, although it's valid.
Probably an easy case.

**Comment by ShiraRotman** [comment]
Hi, I'll take a look. You can assign me to the issue.

**Comment by davidmeirlevy** [comment]
@ShiraRotman Yay!
have you joined our slack workspace?

**Comment by ShiraRotman** [comment]
No, please give me the link.

**Comment by davidmeirlevy** [comment]
https://join.slack.com/t/greenpressworkspace/shared_invite/zt-gkjwvjvl-t1AqxDLx7LOJOK_63JyaqA
